name: generate 3D profile contribution

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v5

      # Step 2: Generate 3D profile contribution using custom JSON
      - name: Generate 3D profile contribution
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: .github/profile-3d-settings.json

      # Step 3: Push generated SVGs to separate branch
      - name: Push 3D profile SVGs
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: profile-3d-output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
